project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 2"
            href: "https://public.tableau.com/app/profile/jiayan.wu/viz/In-Class_Ex02_17771004530650/Dashboard1?publish=yes"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    code-block-bg: "#f8f9fa"
    code-block-border-left: "#31BAE9"
    code-overflow: scroll
    grid:
      body-width: 1100px
      sidebar-width: 250px
      margin-width: 200px
editor: visual

